# Generated by Django 4.1 on 2023-12-01 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_customer_id_alter_order_id_alter_orderitem_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Manillar', 'Manillar'), ('Rueda', 'Rueda'), ('Freno', 'Freno'), ('Sillin', 'Sillin'), ('Camara', 'Camara'), ('Pedal', 'Pedal'), ('Cuadro', 'Sillin'), ('Cambios', 'Cambios')], max_length=200, null=True),
        ),
    ]
