# Generated by Django 4.1 on 2023-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='maker',
            field=models.CharField(choices=[('Berria', 'Berria'), ('BH', 'BH'), ('CBK', 'CBK'), ('Goka', 'Goka'), ('Massi', 'Massi'), ('Megamo', 'Megamo'), ('MMR ', 'MMR '), ('Monty', 'Monty'), ('MSC', 'MSC'), ('Orbea', 'Orbea'), ('Vitoria', 'Vitoria'), ('Unno', 'Unno')], max_length=200, null=True),
        ),
    ]
