# Generated by Django 3.0 on 2023-12-02 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_product_maker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Manillar', 'Manillar'), ('Rueda', 'Rueda'), ('Freno', 'Freno'), ('Sillin', 'Sillin'), ('Camara', 'Camara'), ('Pedal', 'Pedal'), ('Cuadro', 'Cuadro'), ('Cambios', 'Cambios')], max_length=200, null=True),
        ),
    ]
