# Generated by Django 3.0 on 2023-12-02 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20231202_1729'),
        ('store', '0006_alter_product_type'),
    ]

    operations = [
    ]
