# Generated by Django 4.2.7 on 2023-12-02 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_order_estimated_delivery_date_order_refund_granted_and_more'),
        ('store', '0006_alter_product_type'),
    ]

    operations = [
    ]
