# Generated by Django 4.2.7 on 2023-12-02 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_merge_20231202_1813'),
        ('store', '0007_merge_20231202_2011'),
    ]

    operations = [
    ]
