# Generated by Django 4.2.7 on 2023-12-02 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_merge_20231202_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Cuadro', 'Cuadro'), ('Manillar', 'Manillar'), ('Sillin', 'Sillin'), ('Camara', 'Camara'), ('Rueda', 'Rueda'), ('Freno', 'Freno'), ('Pedal', 'Pedal'), ('Cambios', 'Cambios')], max_length=200, null=True),
        ),
    ]
