# Generated by Django 4.2.7 on 2023-12-02 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_product_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
        migrations.AlterField(
            model_name='order',
            name='transaction_id',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the transaction id number', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_no',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the stock number', null=True),
        ),
    ]
