# Generated by Django 4.2.7 on 2023-12-04 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_order_tracking_number_alter_order_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
