# Generated by Django 4.2.7 on 2023-12-04 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_remove_order_tracking_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.IntegerField(blank=True, default=0, help_text='Enter the tracking number id number', null=True),
        ),
    ]
