# Generated by Django 4.2.7 on 2023-12-04 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_order_tracking_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='tracking_number',
        ),
    ]
