# Generated by Django 4.2.7 on 2023-12-07 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_order_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('EA', 'En Almacen'), ('P', 'Procesando'), ('EC', 'En Camino'), ('E', 'Entregado')], default='PL', max_length=2),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('EA', 'En Almacen'), ('P', 'Procesando'), ('EC', 'En Camino'), ('E', 'Entregado')], default='PL', max_length=2),
        ),
    ]
