# Generated by Django 4.1 on 2023-12-04 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Cerrada', 'Cerrada')], default='OPEN', max_length=20),
        ),
    ]
