# Generated by Django 4.1 on 2023-12-04 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='status',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('En progreso', 'En progreso'), ('Cerrada', 'Cerrada')], default='Pendiente', max_length=20),
        ),
    ]
