# Generated by Django 3.0 on 2023-12-06 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_alter_claim_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
